### ISSUE TITLE
Take a look at pybossa as an alternative platform

### ISSUE THREAD

**Issue by arthurlogilab** [ambanum/political-ads-crowdsourcing-client#5]
To keep a record of a discussion started during the open source sprint #bluehats 

Maybe https://pybossa.com/ could be a technical platform to help with this type of crowdsourcing.

**Comment by MattiSG** [comment]
Thanks a lot for the reference @arthurlogilab! I had a look at the platform and it looks quite powerful. Unfortunately quite a few of the [examples](https://pybossa.com/getinspired/) are unavailable and seem outdated.
In any case, the results of this experiment were quite clear in that there is limited need to reproduce it: all detected illegal ads could have been detected with keyword search. However if we ever have to go deeper into crowdsourcing data, I'll make sure Pybossa is on our list, thanks to you 😃 

Closing this issue as there is no intent to change the implementation (and I'll archive this repo as well).
